### ISSUE TITLE
AnyProxy遇到异常退出了

### ISSUE THREAD

**Issue by setamv** [alibaba/anyproxy#126]
平台系统：windows7旗舰版，32位
AnyProxy版本：3.10.3

异常堆栈信息（下面是遇到的2种异常，发生的都非常偶然，大概一天能碰到一次）：
Caught exception: RangeError: Array buffer allocation failed
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at Function.Buffer.concat (buffer.js:309:23)
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\lib\requestHandler.j
s:179:52
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:607:21
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:246:17
    at iterate (D:\Programs\nodejs\node_global\node_modules\anyproxy\node_module
s\async\lib\async.js:146:13)
AnyProxy is about to exit with code: 0

Caught exception: TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at dealWithRemoteResonse (D:\Programs\nodejs\node_global\node_modules\anypro
xy\lib\requestHandler.js:145:65)
    at routeReq (D:\Programs\nodejs\node_global\node_modules\anyproxy\lib\reques
tHandler.js:88:13)
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:607:21
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:246:17
    at iterate (D:\Programs\nodejs\node_global\node_modules\anyproxy\node_module
s\async\lib\async.js:146:13)
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:157:25
    at D:\Programs\nodejs\node_global\node_modules\anyproxy\node_modules\async\l
ib\async.js:248:21
AnyProxy is about to exit with code: 0

**Comment by codingfishman** [comment]
Hi @setamv 
     谢谢反馈！
     是不是AnyProxy一直在运行？第一点初步怀疑是内存消耗导致，需要进一步看看；第二点，可否提供更详细的信息，他是每天固定发生的吗，有没有办法可以获得这时候的header信息？

**Comment by codingfishman** [comment]
Hi @setamv 在所有被AnyProxy所代理的请求中，有无数据流特别大的？

**Comment by setamv** [comment]
您好！
因为anyproxy长时间运行不是很稳定（基本上半天会崩掉一次），我目前已经换了其他的代理了，同样的环境下，其他代理软件运行很长时间了还没遇到过崩溃的情况。
我这里的应用场景是：网页爬虫使用代理对外网进行访问，爬取的都是普通的网页，流量应该也不是非常大，因为网速比较慢（大概2M左右吧）。可能anyproxy所在的主机配置比较差（奔腾G630，2G物理内存。）
AnyProxy运行一段时间后，占用内存是比较大，不过因为我看过几次任务管理器，整个系统的物理内存占用都在60%以下，我就没单独去看AnyProxy的内存占用了。
你提到的header信息，我也尝试过查看与抛出异常比较接近的几个URL，我是将浏览器的代理指向AnyProxy，然后直接在浏览器访问这几个URL，并未发现任何异常，AnyProxy中也可以看到正常访问的日志。因为访问的URL太多，就没有再往前找了
