### ISSUE TITLE
打开失败，SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by winloongLam** [alibaba/anyproxy#141]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Ubuntu 16.04
#### The version of the AnyProxy

AnyProxy 3.10.4

#### Your expected behavior of AnyProxy

正常启动AnyProxy
#### The actual behavior of AnyProxy

启动失败
#### The log of the error

```
/usr/local/lib/node_modules/anyproxy/node_modules/.1.1.0@node-easy-cert/src/index.js:40
  let cache_rootCACrtFileContent, 
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/lib/certMgr.js:4:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by winloongLam** [comment]
我在“...node-easy-cert/src/index.js”文件中CertManager(options)函数的第一行添加了"use strict"后，又提示了certGenerator.js这个文件的错误，将"use strict"添加到certGenerator.js文件的第一行后就可以正常运行了。。。

**Comment by ottomao** [comment]
node-easy-cert@3.1.1 已经修复了这个问题，重装一下anyproxy，应该能解决
