### ISSUE TITLE
用电脑或者苹果手机下载应用时，报错中断。

### ISSUE THREAD

**Issue by YoursJun** [alibaba/anyproxy#187]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

WIN 7
#### The version of the AnyProxy

4.0.0 BETA13

#### Your expected behavior of AnyProxy

能够下载应用包
#### The actual behavior of AnyProxy

用电脑或者苹果手机下载应用时，报错中断。
#### The log of the error

[AnyProxy Log][2017-05-23 16:04:55]: will bypass the man-in-the-middle proxy
[AnyProxy Log][2017-05-23 16:04:55]: received request to: HEAD iosapps.itunes.ap
ple.com/apple-assets-us-std-000001/Purple19/v4/7e/4a/84/7e4a8414-4b87-f789-b573-
62103ab4855d/pre-thinned4406913468493020199.thinned.signed.dpkg.ipa?accessKey=14
95721036_674896863944637729_pSRPY30t0QlSwmNLIAYgrg8RnUYcbqIzMKsbpgwSLBWfCelFLibM
Kucfl9Rdn%2F7s19p6Bq2ycxJnkro6%2BXmBkb30BzDY%2FHrl8FdMwMLup09fzq%2FSR2r67COHD1Dv
CByotvOA9e%2Bmy8P4vyC5VehMjJVPIvnXid6ZY0fhIw2tvmjwHJE2FJlrsvcgH1QbsBvphxak1V5%2B
OsfoGPIXb247%2Bfbb8%2FceOZdfq0nws2BEllw%3D
[AnyProxy Log][2017-05-23 16:04:55]: received request to: HEAD 183.232.189.117/i
osapps.itunes.apple.com/apple-assets-us-std-000001/Purple19/v4/7e/4a/84/7e4a8414
-4b87-f789-b573-62103ab4855d/pre-thinned4406913468493020199.thinned.signed.dpkg.
ipa?accessKey=1495721036_674896863944637729_pSRPY30t0QlSwmNLIAYgrg8RnUYcbqIzMKsb
pgwSLBWfCelFLibMKucfl9Rdn%2F7s19p6Bq2ycxJnkro6%2BXmBkb30BzDY%2FHrl8FdMwMLup09fzq
%2FSR2r67COHD1DvCByotvOA9e%2Bmy8P4vyC5VehMjJVPIvnXid6ZY0fhIw2tvmjwHJE2FJlrsvcgH1
QbsBvphxak1V5%2BOsfoGPIXb247%2Bfbb8%2FceOZdfq0nws2BEllw%3D&wsiphost=local
[AnyProxy Log][2017-05-23 16:04:55]: received request to: GET iosapps.itunes.app
le.com/apple-assets-us-std-000001/Purple19/v4/7e/4a/84/7e4a8414-4b87-f789-b573-6
2103ab4855d/pre-thinned4406913468493020199.thinned.signed.dpkg.ipa?accessKey=149
5721036_674896863944637729_pSRPY30t0QlSwmNLIAYgrg8RnUYcbqIzMKsbpgwSLBWfCelFLibMK
ucfl9Rdn%2F7s19p6Bq2ycxJnkro6%2BXmBkb30BzDY%2FHrl8FdMwMLup09fzq%2FSR2r67COHD1DvC
ByotvOA9e%2Bmy8P4vyC5VehMjJVPIvnXid6ZY0fhIw2tvmjwHJE2FJlrsvcgH1QbsBvphxak1V5%2BO
sfoGPIXb247%2Bfbb8%2FceOZdfq0nws2BEllw%3D
[AnyProxy Log][2017-05-23 16:04:56]: received request to: GET a5.mzstatic.com/us
/r30/Purple117/v4/36/70/b6/3670b674-e942-10f5-5cde-477ad3f60b5e/icon114x114.png
[AnyProxy Log][2017-05-23 16:04:56]: received request to: GET is5.mzstatic.com/i
mage/thumb/Purple19/v4/75/aa/a7/75aaa766-5fa0-1ba4-fb0b-60f74f315d48/1024x768bb-
80.jpg
[AnyProxy Log][2017-05-23 16:04:58]: received https CONNECT request p17-keyvalue
service.icloud.com
[AnyProxy Log][2017-05-23 16:04:58]: will bypass the man-in-the-middle proxy
[AnyProxy Log][2017-05-23 16:05:01]: received https CONNECT request init.itunes.
apple.com
[AnyProxy Log][2017-05-23 16:05:01]: will bypass the man-in-the-middle proxy
[AnyProxy ERROR][2017-05-23 16:05:26]: got an uncaught exception, is there anyth
ing goes wrong in your rule file ?
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:441:15)
    at CommonReadableStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at CommonReadableStream.emit (events.js:188:7)
    at CommonReadableStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at ServerResponse.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13)
    at ServerResponse.emit (events.js:185:7)
    at Socket.ondrain (_http_common.js:214:44)
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : xp.apple.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : p17-keyvalues
ervice.icloud.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : p56-buy.itune
s.apple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : clients4.goog
le.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : www.googleapi
s.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : mtalk.google.
com:5228
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : android.clien
ts.google.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ssl.gstatic.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : accounts.goog
le.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s6.rr.itc.cn:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : m.sohu.com:44
3
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : zz.m.sohu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s.go.sohu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : wuliao.epro.s
ogou.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : i.go.sohu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : imp.optaim.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : img01.sogoucd
n.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s9.rr.itc.cn:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : theta.sogoucd
n.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : images.sohu.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : static.360buy
img.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : pos.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : x.jd.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : dup.baidustat
ic.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : static-alias-
1.360buyimg.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : eclick.baidu.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : img1.360buyim
g.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : im-x.jd.com:4
43
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s2.rr.itc.cn:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s7.rr.itc.cn:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : wn.pos.baidu.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : f11.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : cpro2.baidust
atic.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : img02.sogoucd
n.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : www.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : hpd.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ss1.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ss2.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ss0.bdstatic.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : gss0.bdstatic
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ss0.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : m.baidu.com:4
43
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : s.bdstatic.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : hm.baidu.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : clients1.goog
le.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : afd.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : als.baidu.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : mipcache.bdst
atic.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : cpro.baidusta
tic.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : ubmcmm.baidus
tatic.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : mtalk.google.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : play.itunes.a
pple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : su.itunes.app
le.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : itunes.apple.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : se.itunes.app
le.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : pd-st.itunes.
apple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: destorying https connection : init.itunes.a
pple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : xp.apple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : p17-keyvalueservi
ce.icloud.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : p56-buy.itunes.ap
ple.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : clients4.google.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : www.googleapis.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : mtalk.google.com:
5228
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : android.clients.g
oogle.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ssl.gstatic.com:4
43
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : accounts.google.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s6.rr.itc.cn:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : m.sohu.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : zz.m.sohu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s.go.sohu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : wuliao.epro.sogou
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : i.go.sohu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : imp.optaim.com:44
3
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : img01.sogoucdn.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s9.rr.itc.cn:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : theta.sogoucdn.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : images.sohu.com:4
43
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : static.360buyimg.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : pos.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : x.jd.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : dup.baidustatic.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : static-alias-1.36
0buyimg.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : eclick.baidu.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : img1.360buyimg.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : im-x.jd.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s2.rr.itc.cn:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s7.rr.itc.cn:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : wn.pos.baidu.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : f11.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : cpro2.baidustatic
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : img02.sogoucdn.co
m:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : www.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : hpd.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ss1.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ss2.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ss0.bdstatic.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : gss0.bdstatic.com
:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ss0.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : m.baidu.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : s.bdstatic.com:44
3
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : hm.baidu.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : clients1.google.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : afd.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : als.baidu.com:443

[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : mipcache.bdstatic
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : cpro.baidustatic.
com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : ubmcmm.baidustati
c.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : mtalk.google.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : play.itunes.apple
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : su.itunes.apple.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : itunes.apple.com:
443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : se.itunes.apple.c
om:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : pd-st.itunes.appl
e.com:443
[AnyProxy Log][2017-05-23 16:05:26]: endding https cltSocket : init.itunes.apple
.com:443
[AnyProxy Log][2017-05-23 16:05:26]: clearing cache file...
[AnyProxy Log][2017-05-23 16:05:26]: closing webserver...

**Comment by YoursJun** [comment]
下载同一个应用时，前面几次触发下载请求时 anyproxy 会自动关闭。多次重试后，该应用下载成功时会不显示下载进度，由开始下载变为下载完成。显示下载完成的应用能够正常使用。

**Comment by YoursJun** [comment]
centOS 也会出现下载ios应用时代理程序异常中断。你们的稳定版本在哪里下载？
[AnyProxy ERROR][2017-05-25 14:29:57]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:441:15)
    at CommonReadableStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at CommonReadableStream.emit (events.js:188:7)
    at CommonReadableStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at ServerResponse.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13)
    at ServerResponse.emit (events.js:185:7)
    at Socket.ondrain (_http_common.js:214:44)

**Comment by lionel126** [comment]
我下载视频也会频繁出现这个崩溃   相同版本也是beta13
centos 6.9 node v6.10.3 
用forever守护  导致这台虚拟机死掉 

另一台centos 6.7上运行anyproxy v3.10.4 正常，升级beta13  访问mp4地址 也会崩溃

**Comment by ottomao** [comment]
@lionel126 访问mp4地址崩溃，有具体地址么？

**Comment by lionel126** [comment]
@ottomao 你这一问 我试了一下 果然是有些地址一直崩  有些地址是没问题的
http://uc.cdn.kaiyanapp.com/e84f57989c48f179b7a830458905b35b_1280x720.mp4?t=1496288971&k=f387166c8f2872d5

**Comment by YoursJun** [comment]
@codingfishman 请问什么时候能修复这个问题呢？下载ios应用anyproxy就会挂掉。

[AnyProxy Log][2017-06-19 14:33:58]: received request to: GET 36.250.240.117/iosapps.itunes.apple.com/apple-assets-us-std-000001/Purple117/v4/c8/20/14/c8201494-a280-d5d3-3614-13a442100a3a/pre-thinned1029972820907578090.thinned.signed.dpkg.ipa?accessKey=1498048437_5987288512003247949_2D2ISzOxLiYhoSLa3GW%2FjkHyDqai1b5SVgNqou7WyFYMdSw62vY7IRoNKM%2BYW6L2BT1DKIx9X5TL6DSd2X%2BvBOVrNYa%2BpXyYkqpnsQofEcvOY7o3Bb7RWV3Iv3Nxmj6J1wuFwLttm19HUge72zqAWk3qNPb5SSvOM7aVWron%2F5qKBomlxY9LwSBdRTD9Z3SZoBEO275vc0olrati9ziWDKqIRBMTmnmdYcHSS22ADGo%3D&wsiphost=local
[AnyProxy ERROR][2017-06-19 14:34:08]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:441:15)
    at CommonReadableStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at CommonReadableStream.emit (events.js:188:7)
    at CommonReadableStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at ServerResponse.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13)
    at ServerResponse.emit (events.js:185:7)
    at Socket.ondrain (_http_common.js:214:44)

**Comment by lionel126** [comment]
现在的版本不崩溃了吧 beta16 beta18

**Comment by ottomao** [comment]
AnyProxy 3.x下载大文件的处理策略有问题，4.x Beta版应该已经优化好了。试下？
