### ISSUE TITLE
Linux 安装后不能正常启动

### ISSUE THREAD

**Issue by YoursJun** [alibaba/anyproxy#191]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Linux ubuntu
node v4.7.2
#### The version of the AnyProxy

2017/05/25  sudo npm install -g anyproxy@beta

#### Your expected behavior of AnyProxy

正常启动
#### The actual behavior of AnyProxy

不能启动
#### The log of the error

/usr/local/lib/node_modules/anyproxy/proxy.js:252
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/bin/anyproxy:34:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by YoursJun** [comment]
centos

**Comment by frankie0802** [comment]
centos安装不成功，安装日志：
/home/cloud-disk1/private/pengfei06/node-v6.11.3-linux-x64/bin/anyproxy -> /home/cloud-disk1/private/pengfei06/node-v6.11.3-linux-x64/lib/node_modules/anyproxy/bin.js
/home/cloud-disk1/private/pengfei06/node-v6.11.3-linux-x64/lib
└─┬ anyproxy@3.10.4 
  ├── async@0.9.2 
  ├── async-task-mgr@1.1.0 
  ├─┬ body-parser@1.18.2
。。。。
请问是什么原因呢？谢谢~
