### ISSUE TITLE
Error: hostname is required in https proxy

### ISSUE THREAD

**Issue by MoranXiXi** [alibaba/anyproxy#201]
Linux(ubuntu)平台运行AnyProxy4.0@bate(http这一块的效果还可以)  - 但是运行https错误如下:
#sudo node anyproxy -i
[AnyProxy ERROR][2017-06-16 15:52:03]: Error: hostname is required in https proxy
[AnyProxy ERROR][2017-06-16 15:52:03]: Error: hostname is required in https proxy

**Comment by codingfishman** [comment]
@MoranXiXi 
  `sudo node anyproxy -i` 这里面的 anyproxy 就是安装AnyProxy所提供的那个命令吗？ 有没有加其他参数

**Comment by MoranXiXi** [comment]
@codingfishman 
没有其他参数    整个代码只改了anyproxy文件中的:
//start proxy
  .then(ruleModule => {
    proxyServer = new AnyProxy.ProxyServer({
      type: 'https',
      port: program.port || 443,
      throttle: program.throttle,
      rule: ruleModule,
      webInterface: {
        enable: true,
        webPort: program.web,
      },        
      forceProxyHttps: program.intercept,
      dangerouslyIgnoreUnauthorized: !!program.ignoreUnauthorizedSsl,
      silent: program.silent
    });
    // proxyServer.on('ready', () => {});
    proxyServer.start();
  })

**Comment by MoranXiXi** [comment]
@codingfishman 
[AnyProxy ERROR][2017-06-19 10:23:58]: Error: hostname is required in https proxy
[AnyProxy ERROR][2017-06-19 10:23:58]: Error: hostname is required in https proxy
    at ProxyServer.ProxyCore (/new_data/node_modules/anyproxy/proxy.js:81:13)
    at ProxyServer (/new_data/node_modules/anyproxy/proxy.js:306:5)
    at Promise.catch.then.ruleModule (/new_data/node_modules/anyproxy/bin/anyproxy:57:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by codingfishman** [comment]
@MoranXiXi  请尝试最新的beta版本，看看错误是否孩子啊
