### ISSUE TITLE
本服务器80端口全转发至AnyProxy代理的端口，访问80端口报错

### ISSUE THREAD

**Issue by YoursJun** [alibaba/anyproxy#206]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

CentOS 6.5
#### The version of the AnyProxy

4.0 beta 13

#### Your expected behavior of AnyProxy

能够代理成功
#### The actual behavior of AnyProxy

不能正常代理
#### The log of the error

服务端日志：
[AnyProxy Log][2017-06-20 18:05:14]: received request to: GET init-p01st.push.apple.com/bag
[AnyProxy Log][2017-06-20 18:05:14]: received request to: GET init-p01st.push.apple.com/bag
[AnyProxy Log][2017-06-20 18:05:14]: received request to: GET init-p01st.push.apple.com/bag
[AnyProxy ERROR][2017-06-20 18:05:14]: Error: getaddrinfo ENOTFOUND localhost localhost:80

客户端日志：
# AnyProxy Inner Error
Oops! Error happend when AnyProxy handle the request.
This is an error occurred inside AnyProxy, not from your target website.
Error:
Error: connect EMFILE 127.0.0.1:80 - Local (undefined:undefined)
URL:
/
Error: connect EMFILE 127.0.0.1:80 - Local (undefined:undefined)
at Object.exports._errnoException (util.js:1016:11)
at exports._exceptionWithHostPort (util.js:1039:20)
at internalConnect (net.js:933:16)
at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1062:7)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)

**Comment by codingfishman** [comment]
@YoursJun 
  请问是不是在这个指定的请求上面，AnyProxy代理发生错误？ 可否将这个请求的header信息贴出来，如果方便的话，也可以贴一下reponse的header信息，谢谢

**Comment by YoursJun** [comment]
@codingfishman 我在出口服务器上安装AnyProxy，并且将80端口的请求都进行代理。1080是我设置的AnyProxy的代理端口。
iptables -t nat -A OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 1080

requestDetail.requestOptions.headers
-----------------------------------------
{ Host: 'm.csdn.net',
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'Upgrade-Insecure-Requests': '1',
  Cookie: 'fingerprint=14nDVK0qaQYbaoOTQODL1490760503962; wdata_token=2maAfGxbcosTbJGQwGxd8LjUeSFoOP3FDeEPn1mm47V32N3E1490760503967; __utma=17226283.80905740.1490760503.1497949650.1498012081.9; __utmb=17226283.1.10.1498012081; __utmc=17226283; __utmt=1; __utmz=17226283.1492821325.3.2.utmcsr=so.com|utmccn=(organic)|utmcmd=organic|utmctr=mac%20mini%206%E4%BB%A3; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1495153782; uuid_tt_dd=-890124529454856092_20170303',
  'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/54.0.2840.91 Mobile/14F89 Safari/602.1',
  'Accept-Language': 'zh-cn',
  'Accept-Encoding': 'gzip, deflate',
  Connection: 'keep-alive' }
[AnyProxy Log][2017-06-21 10:28:40]: received request to: GET m.csdn.net/


responseDetail.response.header
------------------------------------------
{ 'Content-Type': 'text/html; charset=utf-8',
  'Proxy-Error': 'true',
  'Proxy-Error-Message': 'Error: socket hang up',
  Date: 'Wed, 21 Jun 2017 02:30:20 GMT',
  Connection: 'close' }
[AnyProxy Log][2017-06-21 10:30:22]: received request to: GET dns.weixin.qq.com/cgi-bin/micromsg-bin/newgetdns?uin=603032707&clientversion=637863474&scene=0&net=1&md5=ec0131725306dcf1e98f2fc660258691&devicetype=android-23&lan=zh_CN&sigver=2

**Comment by YoursJun** [comment]
{ Host: 'www.163.com',
  Connection: 'keep-alive',
  'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/54.0.2840.91 Mobile/14F89 Safari/602.1',
  'Accept-Encoding': 'gzip, deflate, sdch',
  'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4' }
[AnyProxy ERROR][2017-06-21 11:24:33]: Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by bingyanay** [comment]
遇到同样的问题，特定请求：
header:
Host:www.xxx.com:80
Connection:close

报错：
[AnyProxy ERROR][2018-05-04 17:43:58]: Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by guoquanyang** [comment]
# AnyProxy Inner Error
Oops! Error happend when AnyProxy handle the request.
This is an error occurred inside AnyProxy, not from your target website.

Error:
Error: connect ECONNREFUSED 127.0.0.1:80
URL:
/
Error: connect ECONNREFUSED 127.0.0.1:80
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
