### ISSUE TITLE
Mac上启动失败

### ISSUE THREAD

**Issue by ggjjl1** [alibaba/anyproxy#214]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

4.0

#### The log of the error

/usr/local/lib/node_modules/anyproxy/bin/anyproxy:4
const program = require('commander'),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by codingfishman** [comment]
@ggjjl1 
  可能是node版本比较低，请问你的版本是多少？ 如果方便的话，可以升级node到最新版本。

**Comment by codingfishman** [comment]
先关闭，如有更新请重新打开
