### ISSUE TITLE
win10 + node 8.1.2 安装完成无法启动

### ISSUE THREAD

**Issue by whwnow** [alibaba/anyproxy#224]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Windows 10 + Node.js 8.1.2
#### The version of the AnyProxy

4.0.0-beta14

#### Your expected behavior of AnyProxy

正常使用

#### The actual behavior of AnyProxy

报错无法使用

#### The log of the error

```node
PS C:\Users\xxx> anyproxy
module.js:487
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\whwnow\AppData\
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by codingfishman** [comment]
@whwnow 
   抱歉，我们有一个依赖缺失。请先使用 `npm install anyproxy@4.0.0-beta13`来安装上一个beta版本，我们会尽快更新

**Comment by whwnow** [comment]
好的，谢谢

**Comment by codingfishman** [comment]
@whwnow 
版本已更新，可以正常安装
