### ISSUE TITLE
启动失败 SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by webyabo** [alibaba/anyproxy#249]
#### Which platform are you running AnyProxy

mac 
node --version  v5.10.1
#### The version of the AnyProxy

anyproxy --version
4.0.0-beta16
#### The log of the error

/usr/local/lib/node_modules/anyproxy/proxy.js:252
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/bin/anyproxy:34:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by Aladdin-ADD** [comment]
destructuring was supported from node v6.4.0. you can upgrade your node version and try again.

ref: http://node.green

**Comment by codingfishman** [comment]
@webyabo @Aladdin-ADD 
 解构要求版本过高，AnyProxy进行了修改，现在从Nodejs 4即可开始运行，谢谢
