### ISSUE TITLE
Mac下启动出错

### ISSUE THREAD

**Issue by hpustudent** [alibaba/anyproxy#256]
#### Which platform are you running AnyProxy
Mac
#### The version of the AnyProxy
4.0 beta

#### Your expected behavior of AnyProxy
无法启动anyproxy

#### The log of the error
/usr/local/node-v4.6.0/lib/node_modules/anyproxy/proxy.js:253
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/node-v4.6.0/lib/node_modules/anyproxy/bin/anyproxy:34:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by codingfishman** [comment]
@hpustudent 
  由于该语法对node版本要求的最低为6，导致在6以下的node版本中启动失败。我们已经进行了修复，会近期发布，你也可以升级node版本，sorry
