### ISSUE TITLE
Anyproxy will crash when inner portrange is greater than *nix port limitation(65535)

### ISSUE THREAD

**Issue by Kxrr** [alibaba/anyproxy#257]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac

#### The version of the AnyProxy

3.10.4

#### Your expected behavior of AnyProxy

Get proxied response

#### The actual behavior of AnyProxy

The anyproxy server crashes

#### The log of the error

received https CONNECT request github.ocm
==>will forward to local https server
Caught exception: RangeError: "port" argument must be >= 0 and < 65536
    at Server.listen (net.js:1465:13)
    at getPort (/Users/kxrr/WebstormProjects/anyproxy/lib/getPort.js:8:12)
    at async.series.proxyPort (/Users/kxrr/WebstormProjects/anyproxy/lib/requestHandler.js:318:21)
    at /Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:607:21
    at /Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:246:17
    at iterate (/Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/Users/kxrr/WebstormProjects/anyproxy/node_modules/async/lib/async.js:605:19)
AnyProxy is about to exit with code: 0

## Steps to  replay the issue

1. Mock `portrange` to `65536` in `lib/getPort.js`
2. Start anyproxy with args `--intercept`
3. Request by `curl -kx 127.0.0.1:8001  https://github.ocm`
4. Than you will see the anyproxy server crashes

It seems to be a border issue, should have limit it.

**Comment by Kxrr** [comment]
I found this issue when I use `Anyproxy` to deal with https requests in production.

And **aother problem** is these ports used by `httpsServerMgr` seems will never be released until the anyproxy server shutdown.

**Comment by ottomao** [comment]
We have fixed this in v4.x.
