### ISSUE TITLE
3.x版本可以获取到app中的https请求，4.x获取不到

### ISSUE THREAD

**Issue by cloudyhuang** [alibaba/anyproxy#269]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

AnyProxy beta 4.0

#### Your expected behavior of AnyProxy

在4.0中无法取得app中https的请求和相应，只有connect；而在你们master版本，代理能够取得https的请求，证书我重新安装后重新生成并信任到手机中。

![anyproxy](https://user-images.githubusercontent.com/28583179/32101986-001cd968-bb4d-11e7-8b55-27b28eee970b.png)

**Comment by codingfishman** [comment]
@cloudyhuang 
  3.x可以用是不是信任过了3.x版本的证书？ 请尝试重新下载和安装4.x的证书后再看看，证书安装的方式和3.x一样。

**Comment by cloudyhuang** [comment]
我是在4.x重新生成并安装的，3.x的证书pc和手机都删了

**Comment by cloudyhuang** [comment]
重装回3.x版本，浏览器网页打开https都不行了，下面是terminal打印的：

received https CONNECT request m.baidu.com
==>will forward to local https server
err occurred when prepare certs for SNI - Error: EACCES: permission denied, open '/Users/master/.anyproxy_certs/m.baidu.com.key'
err occurred when prepare certs for SNI - Error: EACCES: permission denied, open '/Users/master/.anyproxy_certs/m.baidu.com.key'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1348:33)
    at createCertTaskMgr.addTask.e (/usr/local/lib/node_modules/anyproxy/node_modules/node-easy-cert/src/index.js:77:14)
    at asyncTaskMgr.self.addTask (/usr/local/lib/node_modules/anyproxy/node_modules/async-task-mgr/index.js:35:30)
    at Object.getCertificate (/usr/local/lib/node_modules/anyproxy/node_modules/node-easy-cert/src/index.js:70:23)
    at Object.crtMgr.getCertificate (/usr/local/lib/node_modules/anyproxy/lib/certMgr.js:25:14)
    at SNIPrepareCert.async.series.createSecureContext.key (/usr/local/lib/node_modules/anyproxy/lib/httpsServerMgr.js:24:21)
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:607:21
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:246:17
you may upgrade your Node.js to >= v0.12

**Comment by cloudyhuang** [comment]
![13a39491-b392-47bf-9865-61410e3395a0](https://user-images.githubusercontent.com/28583179/32267199-6178ee96-bf25-11e7-9b2b-1b691702fe7d.png)
已经解决，将.anyproxy_certs文件夹权限改为读和写就ok了

**Comment by cloudyhuang** [comment]
真的还是不行，装回3.x版本，网页、app中的https请求都能抓到，卸载3.x再装4.x版本，网页的https请求响应都可以捕获到，app里的https只有connect没有请求和响应，证书我都是重新生成并安装到手机中的。

**Comment by codingfishman** [comment]
@cloudyhuang  app是内部的app吗，如果是共有app，请给一个示例，我们安装看看

**Comment by cloudyhuang** [comment]
恒大金服 app

**Comment by codingfishman** [comment]
@cloudyhuang 
  有点奇怪，我使用安卓和iOS都安装过恒大金服app，可以正常代理到 `m.hdfax.com`, `static.hdfax.com` 下的请求，app使用也正常。
  
   请做如下操作，帮忙进行定位：
   1. `~/.anyproxy/certificates` 下是否有 `qm.hdfax.com.crt`文件
   2. `https://fdfs.hdfax.com/group1/M00/31/79/CgEIOlnI0xKAc6q9AADSLhpugjM746.png` 以此为例，从手机的浏览器上是否可以访问到
  3. 恒大金服app上的其他请求可否代理到
  4. 手机型号

谢谢

**Comment by JhonSmith0x7b** [comment]
同样的问题, 换到3.x解决了.3q

**Comment by Partenza** [comment]
同样有这问题

**Comment by codingfishman** [comment]
@JhonSmith0x7b  @Partenza 
  3.x和4.0的证书不同，需要单独安装和信任4.0的证书设置，进行完这一步还会出现https无法代理吗

**Comment by 1029219814** [comment]
请问怎么装3.x版本，网上没找到，谢谢

**Comment by codingfishman** [comment]
@1029219814 
   我们推荐使用4.0, 不过你可以通过 `npm install@anyproxy@3.10.3` 来安装3.x的版本

**Comment by titianqx** [comment]
是不是这步没做
iOS >= 10.3信任CA证书
除了上述证书安装过程，还需要在 设置->通用->关于本机->证书信任设置 中把AnyProxy证书的开关打开，否则safari将报错。
http://anyproxy.io/cn/#ios%E7%B3%BB%E7%BB%9F%E4%BF%A1%E4%BB%BBca%E8%AF%81%E4%B9%A6
