### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by shouhou** [alibaba/anyproxy#271]
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

"anyproxy": "^4.0.0-beta18"

node v7.8.0

**Comment by codingfishman** [comment]
@shouhou 
   可否给出更详细的日志方便定位，我本地在node v8环境下没有遇到这个警告，谢谢

**Comment by shouhou** [comment]
(node:9133) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at maybeCallback (fs.js:98:42)
    at Object.fs.writeFile (fs.js:1285:14)
    at Recorder.updateRecordBody (/Users/lingyao/Projects/MeP/cn-proxy/node_modules/_anyproxy@4.0.0-beta9@anyproxy/lib/recorder.js:138:8)
    at Recorder.updateRecord (/Users/lingyao/Projects/MeP/cn-proxy/node_modules/_anyproxy@4.0.0-beta9@anyproxy/lib/recorder.js:96:10)
    at co.then.then.then.then.then.catch.then.then (/Users/lingyao/Projects/MeP/cn-proxy/node_modules/_anyproxy@4.0.0-beta9@anyproxy/lib/requestHandler.js:383:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by codingfishman** [comment]
@shouhou  谢谢反馈，请更新beta版本，问题已修复

**Comment by shouhou** [comment]
@codingfishman 我本地的版本是4.0.0-beta18，beta目前最新版本也是4.0.0-beta18 ，难道有出19？

**Comment by codingfishman** [comment]
Hi @shouhou ,
 从你的日志信息来看，报错的版本似乎是 4.0.0-beta9,

(node:9133) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
at maybeCallback (fs.js:98:42)
at Object.fs.writeFile (fs.js:1285:14)
at Recorder.updateRecordBody (/Users/lingyao/Projects/MeP/cn-proxy/node_modules/_anyproxy@**4.0.0-beta9@anyproxy**/lib/recorder.js:138:8)

你本地的版本指这项目里面的beta版本吗？
