### ISSUE TITLE
在CentOS上无法生成证书

### ISSUE THREAD

**Issue by HelloKevinWu** [alibaba/anyproxy#283]
软件版本：
**CentOS release 6.9 (Final)**
**anyproxy 4.0.0-beta18**

问题：
**# anyproxy --root**

  error: unknown option `--root'

**# anyproxy-ca**
/usr/lib/node_modules/anyproxy/proxy.js:253
        for (const [key, conn] of this.requestHandler.conns) {
                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/anyproxy/bin/anyproxy-ca:11:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by HelloKevinWu** [comment]
**# anyproxy -h**

  Usage: anyproxy [options]

  Options:

    -h, --help                 output usage information
    -V, --version              output the version number
    -p, --port [value]         proxy port, 8001 for default
    -w, --web [value]          web GUI port, 8002 for default
    -r, --rule [value]         path for rule file,
    -l, --throttle [value]     throttle speed in kb/s (kbyte / sec)
    -i, --intercept            intercept(decrypt) https requests when root CA exists
    -s, --silent               do not print anything into terminal
    -c, --clear                clear all the certificates and temp files
    --ignore-unauthorized-ssl  ignore all ssl error

**Comment by codingfishman** [comment]
@HelloKevinWu 
是用anyproxy-ca没错，这段兼容应该已经修复了，你可以更新版本，直接安装AnyProxy正式版即可。
