### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by gucong3000** [alibaba/anyproxy#318]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy
Windows 10
#### The version of the AnyProxy
4.0.4

#### The actual behavior of AnyProxy
报错退出
#### The log of the error
```shell
[AnyProxy Log][2018-01-10 17:49:00]: throttle :10000kb/s
[AnyProxy Log][2018-01-10 17:49:01]: Http proxy started on port 8001
[AnyProxy Log][2018-01-10 17:49:01]: received https CONNECT request raw.githubusercontent.com
[AnyProxy Log][2018-01-10 17:49:01]: will forward to local https server
[AnyProxy Log][2018-01-10 17:49:01]: [internal https]proxy server for raw.githubusercontent.com established
E:\work\anyproxy-rule-mirror\node_modules\brotli\build\encode.js:3
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===

             ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1036:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
```

**Comment by gucong3000** [comment]
```
const request = require('request')
const AnyProxy = require('anyproxy')
const options = {
  port: 8001,
  rule: {},
  webInterface: {
    enable: false,
    webPort: 8002,
    wsPort: 8003
  },
  throttle: 10000,
  forceProxyHttps: true,
  silent: false
}
const proxyServer = new AnyProxy.ProxyServer(options)

proxyServer.on('ready', () => {
  request('https://raw.githubusercontent.com/cnpm/mirrors/master/config/index.js', {
    proxy: 'http://127.0.0.1:8001'
  })
})
proxyServer.on('error', (e) => { /* */ })
proxyServer.start()

// when finished
// proxyServer.close()
```
这是可复现此问题的demo，forceProxyHttps配置为true时会报错

**Comment by codingfishman** [comment]
Hi @gucong3000 
  当配置`forceProxyHttps` 为true，且未安装证书时，AnyProxy所返回的内容不被系统信任，因此返回“unable to verify the first certificate”， 我理解下来，这个返回是AnyProxy已经代理之后的返回不被后续的处理，比如`request`模块所抛出的错误。

 你可以信任安装根证书，或者在使用request模块时，传入参数`rejectUnauthorized: false` 来使其忽略证书错误

**Comment by gucong3000** [comment]
> 你可以信任安装根证书

安装根证书后依然会复现此问题。但是浏览器浏览器中一切正常，且没有证书警告（说明证书安装成功）
之前的`不添加根证书时报错时会报错`的描述有误，安不安证书都报错。

> 在使用request模块时，传入参数`rejectUnauthorized: false`

```js
  request('https://raw.githubusercontent.com/cnpm/mirrors/master/config/index.js', {
    rejectUnauthorized: false,
    proxy: 'http://127.0.0.1:8001'
  })
```
按此方式处理一切正常

**Comment by codingfishman** [comment]
好的，nodejs在使用自签名证书时，可能无法使用系统级别信任的证书，此时你可以指定 `ca: "path/of/your/cert"`选项，来给他设置证书路径，也可以设置`rejectUnauthorized: false`来使用

**Comment by cuixiping** [comment]
@codingfishman 要怎么指定 `ca: "path/of/your/cert"` 选项呢？

我使用 AnyProxy 也碰到上述问题。(已安装根证书到系统了)

我是直接在浏览器设置代理进行访问的，不是像上面那样用node脚本请求。

不用代理访问正常，用 AnyProxy 代理则浏览器提示错误如下图：

![image](https://user-images.githubusercontent.com/1104492/56134523-558ad700-5fc1-11e9-961c-7e32906ea400.png)

**Comment by Stngle** [comment]
> 好的，nodejs在使用自签名证书时，可能无法使用系统级别信任的证书，此时你可以指定 `ca: "path/of/your/cert"`选项，来给他设置证书路径，也可以设置`rejectUnauthorized: false`来使用

要怎么指定 ca: "path/of/your/cert" 选项呢？
