### ISSUE TITLE
访问自签名证书的https网站报错

### ISSUE THREAD

**Issue by Totti0135** [alibaba/anyproxy#340]
访问自签名证书的https网站报错

#### Which platform are you running AnyProxy
linux

#### The version of the AnyProxy
4.0.6

#### Your expected behavior of AnyProxy
可以正常访问自签名证书的https网站

#### The actual behavior of AnyProxy
报错

#### The log of the error
```
Error: unable to verify the first certificate
at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
at emitNone (events.js:106:13)
at TLSSocket.emit (events.js:208:7)
at TLSSocket._finishInit (_tls_wrap.js:637:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```

**Comment by codingfishman** [comment]
@Totti0135 
   如果你是通过命令行启动，请在启动参数上新增： `--ignore-unauthorized-ssl`, 如果你是用node模块，那么可以传入参数： `dangerouslyIgnoreUnauthorized: true`
