### ISSUE TITLE
初始化服务器的时候报错 Browser is not defined

### ISSUE THREAD

**Issue by zuishizhi** [alibaba/anyproxy#368]
我把anyproxy作为模块引入到electronjs里头，报了这个错误。。。我想问下，这个brotli在anyproxy里是做什么用的？

ReferenceError: Browser is not defined
    at Va (/app/node_modules/brotli/build/encode.js:49:191)
    at Object.<anonymous> (/app/node_modules/brotli/build/encode.js:50:304)
    at Module._compile (module.js:685:30)
    at Object.Module._extensions..js (module.js:702:10)
    at Module.load (module.js:598:32)
    at tryModuleLoad (module.js:538:12)
    at Function.Module._load (module.js:530:3)
    at Module.require (module.js:629:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/brotli/compress.js:1:76)

**Comment by kazthehack** [comment]
for future reference:  this is caused by an issue in brotli's compressed build. If you change require("brotli") to require("brotli/decompress") in anyproxy, no problems should be encountered during runtime.

https://github.com/foliojs/brotli.js/issues/20#issuecomment-416766832
