### ISSUE TITLE
Mac anyproxy 4.0.10开启代理报错，代理中断

### ISSUE THREAD

**Issue by wishchen** [alibaba/anyproxy#370]
环境 Mac os 10.13.4
anyproxy 4.0.10
开启代理报错，代理直接中断
```
➜  log anyproxy --intercept
[AnyProxy Log][2018-05-09 12:47:27]: Http proxy started on port 8001
[AnyProxy Log][2018-05-09 12:47:27]: web interface started on port 8002
[AnyProxy Log][2018-05-09 12:47:30]: received https CONNECT request stats.umsns.com
[AnyProxy Log][2018-05-09 12:47:30]: will forward to local https server
[AnyProxy Log][2018-05-09 12:47:30]: [internal https]proxy server for stats.umsns.com established
[AnyProxy Log][2018-05-09 12:47:30]: received request to: GET stats.umsns.com/sdkstats?md5imei=5F87B6AB76EDCC01942193A6D24DC717&ak=5af02e81a40fa37dce00014a&de=FRD-AL00&ek=6472add3e890970ecf36f6b309e8ae01&imei=862679038221980&test=0&useshareview=true&ni=1&isjump=false&sdkv=6.4.2&android_id=82d51605c48754c3&pcv=2.0&mac=5C%3AA8%3A6A%3ACF%3A91%3A81&sn=55CDU16819000329&pkname=com.taoche.b2b&os=Android&stats_type=dau&opid=0&isauth=false&isshare=false&en=Wi-Fi&uid=5f87b6ab76edcc1942193a6d24dc717&os_version=7.0&tp=1&u_sharetype=native&dt=1525841249942
[AnyProxy ERROR][2018-05-09 12:47:30]: Error: getaddrinfo ENOTFOUND stats.umsns.com stats.umsns.com:443
[AnyProxy Log][2018-05-09 12:47:30]: received https CONNECT request ulogs.umeng.com
[AnyProxy Log][2018-05-09 12:47:30]: received https CONNECT request plbslog.umeng.com
[AnyProxy Log][2018-05-09 12:47:30]: will forward to local https server
[AnyProxy Log][2018-05-09 12:47:30]: [internal https]proxy server for ulogs.umeng.com established
[AnyProxy Log][2018-05-09 12:47:30]: will forward to local https server
[AnyProxy Log][2018-05-09 12:47:30]: [internal https]proxy server for plbslog.umeng.com established
[AnyProxy Log][2018-05-09 12:47:30]: received request to: POST ulogs.umeng.com/unify_logs
[AnyProxy Log][2018-05-09 12:47:30]: received request to: POST plbslog.umeng.com/umpx_internal
[AnyProxy Log][2018-05-09 12:47:30]: received request to: GET connectivitycheck.android.com/generate_204
[AnyProxy ERROR][2018-05-09 12:47:30]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
[AnyProxy Log][2018-05-09 12:47:30]: destorying https connection : 127.0.0.1:62560
[AnyProxy Log][2018-05-09 12:47:30]: endding https cltSocket : 127.0.0.1:62560
[AnyProxy Log][2018-05-09 12:47:30]: clearing cache file...
[AnyProxy Log][2018-05-09 12:47:30]: closing webserver...
```
提示rule file有问题，可是没有选用rule文件

**Comment by shinriyo** [comment]
me too in testcafe

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
```

**Comment by hemasama** [comment]
我之前也遇到这个问题，后来把node从10降到8就好了。

**Comment by sannysoft** [comment]
I have the same error with anyproxy 4.0.10, mac and node 10

```
[AnyProxy Log][2018-06-08 13:44:31]: Http proxy started on port 5000
[AnyProxy Log][2018-06-08 13:44:31]: web interface started on port 5001
[AnyProxy Log][2018-06-08 13:44:31]: Active rule is: a rule to hack response
READY
[AnyProxy Log][2018-06-08 13:46:48]: received https CONNECT request safebrowsing.googleapis.com
[AnyProxy Log][2018-06-08 13:46:48]: will forward to local https server
[AnyProxy Log][2018-06-08 13:46:52]: [internal https]proxy server for safebrowsing.googleapis.com established
[AnyProxy Log][2018-06-08 13:46:52]: received request to: GET detectportal.firefox.com/success.txt
[AnyProxy Log][2018-06-08 13:47:03]: received https CONNECT request www.gstatic.com
[AnyProxy Log][2018-06-08 13:47:03]: will forward to local https server
[AnyProxy Log][2018-06-08 13:47:03]: [internal https]proxy server for www.gstatic.com established
[AnyProxy Log][2018-06-08 13:47:03]: received https CONNECT request accounts.google.com
[AnyProxy Log][2018-06-08 13:47:03]: received https CONNECT request www.google.com
[AnyProxy Log][2018-06-08 13:47:03]: will forward to local https server
[AnyProxy Log][2018-06-08 13:47:03]: will forward to local https server
[AnyProxy Log][2018-06-08 13:47:03]: [internal https]proxy server for accounts.google.com established
[AnyProxy Log][2018-06-08 13:47:03]: [internal https]proxy server for www.google.com established
/Users/sanny/Documents/GitHub/jetcompass-proxy/node_modules/brotli/build/encode.js:3
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===
                                                                                                                                                                                                                              ^

Error: read ECONNRESET
    at TCP.onread (net.js:657:25)
```
