### ISSUE TITLE
AnyProxy启动出现错误

### ISSUE THREAD

**Issue by Evil-crow** [alibaba/anyproxy#413]
平台: Fedora 27 x86_64 Linux 4.17.11-100.fc27.x86_64

AnyProxy 版本: 4.0.11

AnyProxy在启动时报错,

```
[localhost@PC]$ anyproxy
module.js:549
    throw err;
    ^

Error: Cannot find module './rootCaCheck'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/anyproxy/bin/anyproxy:10:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```
对js内容,了解不多,请问如何能够解决这个问题?

**Comment by codingfishman** [comment]
@Evil-crow 
  不好意思，请重新安装AnyProxy，我们这个大小写进行了修正

**Comment by Evil-crow** [comment]
@codingfishman 感谢您的回复,现在已经可以正常启动了
可以请问一下在Linux上如何导入CA, 目前PC浏览器没有抓包到的结果
在```anyproxy -i```时,一直提示```ROOT CA```未被导入,面对生成的rootCA.crt不知道怎么下手
OS: Fedora Linux
在之前的issue中也有人提问,不过暂时还没有回答.谢谢.

**Comment by codingfishman** [comment]
@Evil-crow 
  确实没有试过fedora系统，不过google到相关资料你可以试试，这个： https://chewett.co.uk/blog/841/installing-root-certificate-authority-fedora-26/

**Comment by Evil-crow** [comment]
@codingfishman 十分感谢您的帮助,AnyProxy现在已经可以正常工作了
十分好用的工具,谢谢.
