### ISSUE TITLE
Ubuntu启动报错

### ISSUE THREAD

**Issue by Antecer** [alibaba/anyproxy#428]
···
root@antproxy:~# anyproxy -port 8001
/usr/local/lib/node_modules/anyproxy/node_modules/inquirer/lib/prompts/list.js:32                                               
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);                                      
                                                             ^                                                                  
                                                                                                                                
SyntaxError: Unexpected token {                                                                                                 
    at exports.runInThisContext (vm.js:53:16)                                                                                   
    at Module._compile (module.js:374:25)                                                                                       
    at Object.Module._extensions..js (module.js:417:10)                                                                         
    at Module.load (module.js:344:32)                                                                                           
    at Function.Module._load (module.js:301:12)                                                                                 
    at Module.require (module.js:354:17)                                                                                        
    at require (internal/module.js:12:17)                                                                                       
    at Function.promptModule.restoreDefaultPrompts (/usr/local/lib/node_modules/anyproxy/node_modules/inquirer/lib/inquirer.js:5
5:33)                                                                                                                           
    at Object.inquirer.createPromptModule (/usr/local/lib/node_modules/anyproxy/node_modules/inquirer/lib/inquirer.js:65:16)    
    at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/node_modules/inquirer/lib/inquirer.js:77:28)                    
    at Module._compile (module.js:410:26)                                                                                       
    at Object.Module._extensions..js (module.js:417:10)                                                                         
    at Module.load (module.js:344:32)                                                                                           
    at Function.Module._load (module.js:301:12)                                                                                 
    at Module.require (module.js:354:17)                                                                                        
    at require (internal/module.js:12:17)
···

**Comment by laysent** [comment]
可以升级一下 node.js 的版本看看

**Comment by codingfishman** [comment]
@Antecer 
请升级nodejs到6以后再看看
