### ISSUE TITLE
接受到一个请求后， anyproxy报错，自动关闭

### ISSUE THREAD

**Issue by SongZhenhuawandou** [alibaba/anyproxy#430]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

Mac
#### The version of the AnyProxy

4.0.12

#### The log of the error

[AnyProxy Log][2018-10-11 16:09:10]: received request to: GET www.localnetwork.uop/
[AnyProxy ERROR][2018-10-11 16:09:10]: Error: getaddrinfo ENOTFOUND www.localnetwork.uop www.localnetwork.uop:80
[AnyProxy ERROR][2018-10-11 16:09:11]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[AnyProxy Log][2018-10-11 16:09:11]: destorying https connection : 127.0.0.1:62976
[AnyProxy Log][2018-10-11 16:09:11]: endding https cltSocket : 127.0.0.1:62976
[AnyProxy Log][2018-10-11 16:09:11]: clearing cache file...
[AnyProxy Log][2018-10-11 16:09:11]: ==>>> clearing cache 
[AnyProxy Log][2018-10-11 16:09:11]: closing webserver...

**Comment by zhifengmuyu** [comment]
Met the same issue, on Mac, anyproxy V4.0.12

**Comment by ningdb** [comment]
me too.

**Comment by pytpeng** [comment]
i met same issue(when my node version was 10), maybe you should check your node version. Now i use 8,  it is stable

> Plese fill the template when you reporting a new issue, thanks!
> 
> #### Which platform are you running AnyProxy
> Mac
> 
> #### The version of the AnyProxy
> 4.0.12
> 
> #### Your expected behavior of AnyProxy
> #### The actual behavior of AnyProxy
> #### The log of the error
> [AnyProxy Log][2018-10-11 16:09:10]: received request to: GET [www.localnetwork.uop/](http://www.localnetwork.uop/)
> [AnyProxy ERROR][2018-10-11 16:09:10]: Error: getaddrinfo ENOTFOUND [www.localnetwork.uop](http://www.localnetwork.uop) [www.localnetwork.uop:80](http://www.localnetwork.uop:80)
> [AnyProxy ERROR][2018-10-11 16:09:11]: got an uncaught exception, is there anything goes wrong in your rule file ?
> Error: read ECONNRESET
> at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> [AnyProxy Log][2018-10-11 16:09:11]: destorying https connection : 127.0.0.1:62976
> [AnyProxy Log][2018-10-11 16:09:11]: endding https cltSocket : 127.0.0.1:62976
> [AnyProxy Log][2018-10-11 16:09:11]: clearing cache file...
> [AnyProxy Log][2018-10-11 16:09:11]: ==>>> clearing cache
> [AnyProxy Log][2018-10-11 16:09:11]: closing webserver...

i met same issue(when my node version was 10), maybe you should check your node version. Now i use 8,  it is stable

**Comment by codingfishman** [comment]
thanks @pytpeng 
@SongZhenhuawandou @zhifengmuyu @ningdb can you change a node version and take a try. BTW, are you all in node 10 now?

**Comment by SongZhenhuawandou** [comment]
@codingfishman , my node version is 10.10.0

**Comment by cnnblike** [comment]
replicable w/ node version 11.3.0

**Comment by AngryMills** [comment]
version 8 is ok。

**Comment by iwater** [comment]
https://github.com/alibaba/anyproxy/pull/454
