### ISSUE TITLE
fs.writeFile 在 Node 10 下强制需要传入回调函数，导致这里会报错

### ISSUE THREAD

**Issue by dickeylth** [alibaba/anyproxy#452]
https://github.com/alibaba/anyproxy/blob/2db0fa46260d91b1c54b193502d72a27e574e671/lib/recorder.js#L103

node 10 开始 fs 异步操作必须要传回调函数，导致这里的代码升级 node 10 之后就报错挂了……https://github.com/nodejs/node/blob/master/doc/api/deprecations.md#dep0013-fs-asynchronous-function-without-callback

```
(node:89157) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
  at maybeCallback (fs.js:129:9)
  at Object.writeFile (fs.js:1159:14)
  at Recorder.self.updateRecordBody (/Users/dickeylth/dev/gitlab/test/devserver-test/node_modules/_anyproxy@3.10.4@anyproxy/lib/recorder.js:103:12)
  at Recorder.self.updateRecord (/Users/dickeylth/dev/gitlab/test/devserver-test/node_modules/_anyproxy@3.10.4@anyproxy/lib/recorder.js:64:14)
```

**Comment by ottomao** [comment]
fixed in v3.10.5
