### ISSUE TITLE
I want to use the AnyProxy to proxy server, but i get an error, recorder is required

### ISSUE THREAD

**Issue by fangzhengL** [alibaba/anyproxy#475]
####_ Which platform are you running AnyProxy

Mac 
`const options = { `
     `port: 8001,`
     `// rule: require('myRuleModule'),`
    `webInterface: {`
     `enable: true,`
     `webPort: 8002,`
  `},`
 ` throttle: 10000,`
  `forceProxyHttps: false,`
 ` wsIntercept: false, // 不开启websocket代理`
 ` silent: false,`
`};`
`const anyproxyInstance = new ProxyCore(options);`
`anyproxyInstance.start()`

#### The version of the AnyProxy

 AnyProxy : 4.0.12
Node: 10.15.3

#### Your expected behavior of AnyProxy

I want to use the AnyProxy to proxy server

#### The actual behavior of AnyProxy

I get an error

#### The log of the error

App threw an error during load
Error: recorder is required
    at new ProxyCore (/Users/liangfz/Desktop/Project/H5-KingFish/node_modules/anyproxy/proxy.js:88:13)
    at Object.<anonymous> (/Users/liangfz/Desktop/Project/H5-KingFish/server/index.js:27:26)
    at Object.<anonymous> (/Users/liangfz/Desktop/Project/H5-KingFish/server/index.js:117:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liangfz/Desktop/Project/H5-KingFish/main/index.js:14:1)
    at Object.<anonymous> (/Users/liangfz/Desktop/Project/H5-KingFish/main/index.js:171:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)

**Comment by guox191** [comment]
Hello, I think you wanted to use `new AnyProxy.ProxyServer({ … })` rather than the `ProxyCore`. If you want to have a custom recorder to save network requests data, you may need to initialise the `ProxyCore` and pass your custom recoreder as one of the options.

Thanks!

**Comment by fangzhengL** [comment]
@guox191 I'm wrong,  use `new AnyProxy.ProxyServer({ … })` is working
Thanks!
