### ISSUE TITLE
Caught exception: Error: read ECONNRESET

### ISSUE THREAD

**Issue by netroby** [alibaba/anyproxy#488]
Plese fill the template when you reporting a new issue, thanks!

#### Which platform are you running AnyProxy

android, ubuntu x64 18.10
#### The version of the AnyProxy

3.0 latest
#### The actual behavior of AnyProxy

[internal https]proxy server for push.services.mozilla.com established
Caught exception: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:167:27)
AnyProxy is about to exit with code: 0

#### The log of the error

[internal https]proxy server for push.services.mozilla.com established
Caught exception: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:167:27)
AnyProxy is about to exit with code: 0

**Comment by Huang-Jacky** [comment]
I have met the same error while request a url through anyproxy to real server.

logs as below:
received request to : sg01.rayjump.com/onlyImpression?k=5d06831faa725a12e69d9a9x&p=MTI0NDF8OTI3NjJ8MzU4MTF8MHwwfHxvcGVuYXBpfHwxMjh4MTI4fDd8fHx8fHx8Q058fHx8Z290azFfYWRzZXJ2ZXJ8fE1Ob3JtYWxBbHBoYU1vZGVsUmFua2VyOzI1OzA7MDsyNTswOzA7MV9tb29jX2V4cDEtMl9iYXNlLTk5OTlfMDszfDVkMDY4MzFmYWE3MjVhMTJlNjlkOWE5eHw1ZDA2ODMxZmFhNzI1YTEyZTY5ZDlhOXh8fDF8MHxNb3ppbGxhJTJGNS4wJTIwJTI4TGludXglM0IlMjBBbmRyb2lkJTIwOSUzQiUyMFNNLUc4ODcwJTIwQnVpbGQlMkZQUFIxLjE4MDYxMC4wMTElM0IlMjB3diUyOSUyMEFwcGxlV2ViS2l0JTJGNTM3LjM2JTIwJTI4S0hUTUwlMkMlMjBsaWtlJTIwR2Vja28lMjklMjBWZXJzaW9uJTJGNC4wJTIwQ2hyb21lJTJGNzQuMC4zNzI5LjE1NyUyME1vYmlsZSUyMFNhZmFyaSUyRjUzNy4zNnx8NWQwNjgzMWZhYTcyNWExMmU2OWQ5YTl4fHx8fHwxMy4xMjUuMTk4LjY5fHx8fHx8MS4wfHx8fHx8MzAzNnwxfDkyNzYyfDF8OXx8fHxbWyIyOTM2NjkzMzEiLCI5MDMiLCIiLCIiLCIiLCIxIiwiNWQwNjgzMWZhYTcyNWExMmU2OWQ5Y2R4IiwiIl1dfHwwfHx8fGNvbS5taW50ZWdyYWwuc2RrLmRlbW98fDF8fDR8MHx8dGVzdC5tdGcuY258MHx8fHwwfDMwMnx8fHx8fHwwfHx8fHx8MHx8fHwwfHx8QXBhY2hlLUh0dHBDbGllbnQlMkZVTkFWQUlMQUJMRSUyMCUyOGphdmElMjAxLjQlMjl8fHx8fHx8fHxzYW1zdW5nfHNtLWc4ODcw&csp=i%2BMM6acIfnN2ibMeGUv1idMe6acI&c=287%7C1%7C9%7CMAL_9.12.0%7CSM-G8870%7C1080x2340%7C1%7Czh%7C9%7C%7C%7C1496e5bb140b%7C5d3984ae73511758%7Ce67f4957-0b06-4dd5-9fc9-ed23313a0f60%7C%7Csamsung%7C%7C417b32bf-e32b-5413-a681-4afbc290086d%2C&rs=
==>will forward to real server by proxy
Caught exception: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
AnyProxy is about to exit with code: 0

anyproxy version: 3.10.6
platform: Mac OS 10.12.6
Node.js version: v10.15.3

**Comment by lefuturiste** [comment]
same error here

**Comment by xhurongna** [comment]
log as below:
[internal https]proxy server for imapi.lianjia.com established
Caught exception: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
AnyProxy is about to exit with code: 0

anyproxy version: 3.10.6
platform: Windows X64
Node.js version: v10.16.0
