### ISSUE TITLE
import anyproxy as a module but the script start error

### ISSUE THREAD

**Issue by QiuQiu0034** [alibaba/anyproxy#49]
I wrote a simple script in accordance with the instructions.
But the script start error in idea.

blow is my code:

```
var proxy = require("anyproxy");

//create cert when you want to use https features
//please manually trust this rootCA when it is the first time you run it
//!proxy.isRootCAFileExists() && proxy.generateRootCA();

var options = {
    type          : "http",
    port          : 8088,
    hostname      : "localhost",
    rule          : require("./rule.js")
};
new proxy.proxyServer(options);
```

blow is the console output:

```
"D:\JetBrains\IntelliJ IDEA 14.1.4\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" proxy2.js
===========
failed to create cert dir ,please create one by yourself - \Users\QiuQiu\.anyproxy_certs\
this error will not block main thread unless you use https-related features in anyproxy
===========
this is a blank rule for AnyProxy
Anyproxy rules initialize finished, have fun!
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.module.exports.generateCacheDir (e:\idea_workspace\web-port\node_modules\anyproxy\lib\util.js:49:26)
    at new Recorder (e:\idea_workspace\web-port\node_modules\anyproxy\lib\recorder.js:16:31)
    at e:\idea_workspace\web-port\node_modules\anyproxy\proxy.js:100:43
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)

Process finished with exit code 1

```

**Comment by codingfishman** [comment]
@QiuQiu0034 
   异常里面的提示是说创建目录` \Users\QiuQiu\.anyproxy_certs\`失败了，不知道最新版的anyproxy是否还会出现这个问题？

**Comment by codingfishman** [comment]
关闭issue，有需要可再次打开
