### ISSUE TITLE
after a while, anyproxy crashed

### ISSUE THREAD

**Issue by iwantofun** [alibaba/anyproxy#50]
Caught exception: TypeError: Object #<Object> has no method 'access'
    at Recorder.self.getBody (/Users/xxxx/node_modules/anyproxy/lib/recorder.js:112:12)
    at /Users/xxxx/node_modules/anyproxy/lib/recorder.js:134:18
    at callback (/Users/xxxx/node_modules/anyproxy/node_modules/nedb/lib/executor.js:30:17)
    at Cursor.execFn (/Users/xxxx/node_modules/anyproxy/node_modules/nedb/lib/datastore.js:417:12)
    at Cursor._exec (/Users/xxxx/node_modules/anyproxy/node_modules/nedb/lib/cursor.js:172:17)
    at /Users/xxxx/node_modules/anyproxy/node_modules/nedb/lib/executor.js:40:13
    at Object.q.process [as _onImmediate](/Users/xxxx/node_modules/anyproxy/node_modules/nedb/node_modules/async/lib/async.js:731:21)
    at processImmediate [as _immediateCallback](timers.js:336:15)
AnyProxy is about to exit with code: 0

**Comment by d1ves** [comment]
@iwantofun 

npm install -g access

**Comment by codingfishman** [comment]
@iwantofun 
   是否仍然有crash的问题？如果有的话还请告知版本号：）

**Comment by codingfishman** [comment]
fs.access是在 nodejs ` v0.11.15`引入，因此会导致方法未找到。可升级nodejs版本，也可安装polyfill。
