### ISSUE TITLE
AnyProxy Inner Error

### ISSUE THREAD

**Issue by MeFelixWang** [alibaba/anyproxy#581]
anyproxy版本：4.1.3；

windows平台；

请求部分网站会出现 AnyProxy Inner Error，如下图：

![anyproxy_error](https://user-images.githubusercontent.com/26833355/104541369-7a135780-565c-11eb-8655-9e89bcd6cdaf.png)

**Comment by lyhiving** [comment]
同样遇到，去掉对应的自定义规则也无解

**Comment by 5amch3n** [comment]
也碰到了类似的错误，刷新页面后有时候能正常加载出目标页面，但更多时候是刷新页面后依然报这个错误。

# AnyProxy Inner Error

Error: socket hang up
at createHangUpError (_http_client.js:334:17)
at TLSSocket.socketCloseListener (_http_client.js:375:25)
at TLSSocket.emit (events.js:199:15)
at net.js:593:12
at TCP.done (_tls_wrap.js:441:7)
