### ISSUE TITLE
throttle不支持小数？

### ISSUE THREAD

**Issue by zaaack** [alibaba/anyproxy#80]
anyproxy --throttle 0.1
throttle :0.1kb/s
/usr/local/lib/node_modules/anyproxy/node_modules/stream-throttle/src/throttle.js:54
        throw new Error('throttle rate must be a positive number');
        ^

Error: throttle rate must be a positive number
    at new ThrottleGroup (/usr/local/lib/node_modules/anyproxy/node_modules/stream-throttle/src/throttle.js:54:15)
    at new proxyServer (/usr/local/lib/node_modules/anyproxy/proxy.js:85:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/anyproxy/bin.js:86:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by codingfishman** [comment]
确实，当前没有将小数考虑到，不好意思，会尽快修复发布，谢谢反馈！

**Comment by codingfishman** [comment]
@zaaack 
    讨论过后，我们想知道，在什么样的场景下会使用形如0.9kb的throttle配置，可否描述一下场景。目前默认要求最小值为1，抱歉

**Comment by zaaack** [comment]
@codingfishman 不好意思，是我没说清楚，当时的需求是模拟一个国外第三方服务的脚本抽风的情况，只有800多byte，throttle最小1kb根本模拟不出来，而且配置文件也是同步的，不能用settimeout之类，最后不得不使用死循环实现延时。。这种需求也许并不多，不过最好还是希望能实现异步或者改进throttle。。

**Comment by ottomao** [comment]
如果真要按800 byte这么精确来限速，AnyProxy可能还不合适。
AnyProxy对请求中的小部分内容做过处理，会多多少少影响几个byte，如果对精度要求太高，这个有难度...

**Comment by zaaack** [comment]
@ottomao 我当时所需要最主要的还是是延时功能，并不精确，如果api能做成异步的，可以使用settimeout我觉得比throttle效果可能更好。。毕竟throttle无法完全模拟真实网络中断网的情况。。

**Comment by codingfishman** [comment]
@zaaack 
   借助rule里面的 `replaceServerResDataAsync(req, res, resData, cb)` ，异步调用cb后才会返回到客户端，可否满足你的需求？

**Comment by zaaack** [comment]
@codingfishman 额，是的，当时可能没仔细读文档，原来是有个异步api的哈。抱歉。。
