### ISSUE TITLE
AnyProxy不能在一台机器上同时开启两个实例

### ISSUE THREAD

**Issue by yanqian** [alibaba/anyproxy#82]
以命令`anyproxy -i 8001`开启一个anyproxy实例之后,
再次输入命令`anyproxy -i 8004`打开另外一个anyproxy实例，
有一下错误提示：

```
Caught exception: Error: listen EADDRINUSE :::8001
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at async.series.self.ws.wsServer.port (/usr/local/lib/node_modules/anyproxy/proxy.js:133:38)
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:607:21
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:246:17
    at iterate (/usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:146:13)
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:157:25
AnyProxy is about to exit with code: 0
```

**Comment by ottomao** [comment]
感谢反馈，问题已知，近期会做修复。

**Comment by lol666666** [comment]
请问是不是目前还未修复？

**Comment by yanqian** [comment]
@lol666666 没有好。
`anyproxy -p 8001 -w 8002`
![image](https://cloud.githubusercontent.com/assets/2221926/21474237/51b449d2-cb57-11e6-9cbc-864f8e098e3d.png)
`anyproxy -p 8003 -w 8004`
![image](https://cloud.githubusercontent.com/assets/2221926/21474242/6a5dd5b6-cb57-11e6-95f4-6d979f866536.png)

**Comment by ottomao** [comment]
升级到v3.10.4，使用 -e 参数指定一个websocket端口
