### ISSUE TITLE
anyproxy dora中运行一段时间后出现 The header content contains invalid characters

### ISSUE THREAD

**Issue by IDrinkMoreWater** [alibaba/anyproxy#92]
webpack: bundle build is now finished.
Caught exception: TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at dealWithRemoteResonse (E:\egodrug-weixin-backstage\node_modules\dora-anyp
roxy\lib\requestHandler.js:148:65)
    at routeReq (E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\lib\requ
estHandler.js:89:13)
    at E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modules\async
\lib\async.js:607:21
    at E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modules\async
\lib\async.js:246:17
    at iterate (E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modu
les\async\lib\async.js:146:13)
    at E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modules\async
\lib\async.js:157:25
    at E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modules\async
\lib\async.js:248:21
    at E:\egodrug-weixin-backstage\node_modules\dora-anyproxy\node_modules\async
\lib\async.js:612:34
    at IncomingMessage.<anonymous> (E:\egodrug-weixin-backstage\node_modules\dor
a-anyproxy\lib\requestHandler.js:78:13)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
AnyProxy is about to exit with code: 0

就运行后放置一段时间，什么都不干，也不做任何请求过一会儿就出现了
看错误根源是request的包的错误，但request官方issues看有人说request2.71之后版本好像解决了但不太确定，不知道anyproxy 中为什么还会出现

**Comment by codingfishman** [comment]
Hi @IDrinkMoreWater 
   AnyProxy的业务代码，并没有使用request这个包，而是使用原生的Node_Http, 不过看你的log，用的应该是dora_anyproxy, 而不是AnyProxy。
   这个异常时必现的吗，如果是这样，可否把每次的header信息打印出来（可以直接修改源码），看看出错的那次，header内容是怎么样的？

**Comment by JacksonTian** [comment]
这个问题是setHeader的时候，值有不符合规范的字符存在。

**Comment by IDrinkMoreWater** [comment]
@codingfishman 
AnyProxy有依赖引用request包的，你可以在node_modules目录下找到，问题不出在dora_anyproxy上，因为我把dora_anyproxy替换成完整版的AnyProxy后错误异常，以下是我捕获的在AnyProxy出现异常时的头部信息：
received request to : 10.10.10.105:8989/
==>will forward to real server by proxy
{ hostname: '127.0.0.1',
  port: '8001',
  path: '/',
  method: 'POST',
  headers:
   { Host: '10.10.10.105:8989',
     Referer: '\u0000',
     'Content-Length': 0 },
  rejectUnauthorized: false }
Caught exception: TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at dealWithRemoteResonse (E:\egodrug-weixin-backstage\node_modules\anyp
roxy\lib\requestHandler.js:146:65)
    at routeReq (E:\egodrug-weixin-backstage\node_modules\anyproxy\lib\requ
estHandler.js:88:13)
    at E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modules\async
\lib\async.js:607:21
    at E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modules\async
\lib\async.js:246:17
    at iterate (E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modu
les\async\lib\async.js:146:13)
    at E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modules\async
\lib\async.js:157:25
    at E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modules\async
\lib\async.js:248:21
    at E:\egodrug-weixin-backstage\node_modules\anyproxy\node_modules\async
\lib\async.js:612:34
    at IncomingMessage.<anonymous> (E:\egodrug-weixin-backstage\node_modules\anyproxy\lib\requestHandler.js:77:13)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
AnyProxy is about to exit with code: 0
看日志是Referer出现了一个'\u0000'的问题？，\u0000本身就是''空串的unicode，不知为何会出现，我的服务部署后是没有人访问的，静置一段时间后就出现了，时间不固定
希望能处理下这个问题，如果不能处理至少给出方法捕获下，因为一出现这个错，node进程就整个退出了，服务都完蛋了，还蛮严重的

**Comment by IDrinkMoreWater** [comment]
知道为什么出现了，公司最近在做主机漏洞扫描，所以才有特殊的头部和字符的出现，但也不应该让整个代理服务挂掉吧，这样部署的服务就完蛋了，希望捕获下异常

**Comment by codingfishman** [comment]
Hi @IDrinkMoreWater 
    谢谢反馈，如你所说，当有非法的头部， 如 ‘\u0000'放在header对象中的时候，Node会对其抛出异常，由于AnyProxy没有处理进而导致进程终止（node_modules下面有request包，主要用与测试用例，AnyProxy的业务代码没有对其依赖：）。
   我们将在新版本中进行修复，AnyProxy会对这些内部产生的异常处理加以完善， 谢谢！
