### ISSUE TITLE
刚测试新版本，启动出错，是缺了什么吗

### ISSUE THREAD

**Issue by ayooay** [alibaba/anyproxy#93]
root@one-hk-01:~# anyproxy --version
3.10.3
root@one-hk-01:~# node --version
v0.12.15
root@one-hk-01:~# anyproxy
/usr/lib/node_modules/anyproxy/lib/certMgr.js:25
    easyCert.getCertificate(host, (error, keyContent, crtContent) => {
                                                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/anyproxy/proxy.js:12:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by codingfishman** [comment]
Hi @ayooay 
    AnyProxy正在向ES6靠近，从你的log来看，是当前的Node版本不支持箭头函数（=>)，可否升级版本。
    箭头函数在V4.3.2的node版本中开始支持，可查看 http://node.green/#arrow-functions
